FROM openjdk:11

EXPOSE 8097

RUN apt-get update && apt-get install -y git \
    && rm -rf /var/lib/apt/lists/* \
    && git clone https://github.com/Heyko12/ISD_3rd_LAB_BIT.git \
    && rm -rf /ISD_3rd_LAB_BIT/task1 ISD_3rd_LAB_BIT/task2/Producer docker* Docker* init.sh my.cnf mysqlscript.sql

WORKDIR /ISD_3rd_LAB_BIT/task2/Consumer

RUN javac Main.java

CMD [""]