CREATE TABLE IF NOT EXISTS mytable (timestamp VARCHAR(255) PRIMARY KEY, jsoned_line VARCHAR(1023));
CREATE USER IF NOT EXISTS 'user'@'172.18.0.2' IDENTIFIED BY 'password';
FLUSH PRIVILEGES;
GRANT ALL PRIVILEGES ON mydatabase.* TO 'user'@'172.18.0.2' WITH GRANT OPTION;